version: "3.8"
services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      TZ: "Europe/Berlin"
      WEBPASSWORD: "changeMe123!"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      # - "67:67/udp" # nur falls Pi-hole auch DHCP machen soll
    volumes:
      - pihole_etc:/etc/pihole
      - dnsmasq_etc:/etc/dnsmasq.d
volumes:
  pihole_etc:
  dnsmasq_etc:
